
@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJpbWxhbHZ0NnlyIiwiaWF0IjoxNjczNDI0NTI2fQ.X57SHYOoHtE7gODATPYx7cYkIWwNDj0aW89Tw4NNulQ

### test
POST {{host}}/GetData
Content-Type: application/json
Authorization: {{token}}

{}

### login
POST {{host}}/user/Login
Content-Type: application/json

{
    "username": "lixudong",
    "password":"123"
}

### register

POST {{host}}/user/Register
Content-Type: application/json

{
    "username": "lixudong",
    "password": "123"
}

### changeRoles
POST {{host}}/user/ChangeRole
Authorization: {{token}}
Content-Type: application/json

{
    "uid": "uadnb7bhfy",
    "roles": ["admin"]
}