
@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJpNWszaWhxN2hxIiwiaWF0IjoxNjczNTEzMjI4fQ.Eu3112zY8xZ9HtBxsZtIXMY2bNtt-eOX5CFKD1VcDfM

### test
POST {{host}}/GetData
Content-Type: application/json
Authorization: {{token}}

{}

### login
POST {{host}}/user/Login
Content-Type: application/json

{
    "username": "lixudong",
    "password":"123"
}

### register

POST {{host}}/user/Register
Content-Type: application/json

{
    "username": "lixudong",
    "password": "123"
}

### changeRoles
POST {{host}}/user/ChangeRole
Authorization: {{token}}
Content-Type: application/json

{
    "uid": "i5k3ihq7hq",
    "roles": ["admin"]
}

### post add
POST {{host}}/post/AddPost
Authorization: {{token}}
Content-Type: application/json

{
    "title": "文章标题2",
    "content": "文章内容"
}

### get all post
POST {{host}}/post/GetAllPost
Authorization: {{token}}
Content-Type: application/json

{
    "page": 1,
    "size": 10
}

### update post
POST {{host}}/post/UpdatePost
Authorization: {{token}}
Content-Type: application/json

{
    "tagId": 3,
    "id": 1
}

### add tag

POST {{host}}/tag/Add
Authorization: {{token}}
Content-Type: application/json

{
    "name": "标签1"
}

### get all tag
POST {{host}}/tag/GetAll
Authorization: {{token}}
Content-Type: application/json

{
}
### get user tag
POST {{host}}/user/GetTags
Authorization: {{token}}
Content-Type: application/json

{
}