// Generated by prisma-generator-tsrpc v1.0.13



/* Model 用户 */
export type UserFull = {
    /* ID 主键 */
    id: number;
    /* uid */
    uid: string;
    /* 昵称 */
    nickName: string;
    /* 用户名 */
    username: string;
    /* 密码 */
    password: string;
    /* 文章 */
    posts: Post[];
    /* 标签 */
    tags: Tag[];
    /* 权限 */
    roles: string[];
};

/* Model 用户 */
export type User = {
    /* ID 主键 */
    id: number;
    /* uid */
    uid: string;
    /* 昵称 */
    nickName: string;
    /* 用户名 */
    username: string;
    /* 密码 */
    password: string;
    /* 权限 */
    roles: string[];
};

/* Model User Relation All */
export type UserRelation = {
    /* 文章 */
    posts: Post[];
    /* 标签 */
    tags: Tag[];
};

/* Model User Relation Posts */
export type UserPostsRelation = {
    /* 文章 */
    posts: Post[];
};

/* Model User Relation Tags */
export type UserTagsRelation = {
    /* 标签 */
    tags: Tag[];
};

/* Model 文章 */
export type PostFull = {
    /* ID 主键 */
    id: number;
    /* 标题 */
    title: string;
    /* 内容 */
    content: string;
    /* 是否已发布 */
    pubished: boolean;
    /* 作者 */
    author: User;
    /* 作者id */
    authorId: number;
    /* 标签 */
    Tag?: Tag | null;
    /* 标签id */
    tagId?: number | null;
};

/* Model 文章 */
export type Post = {
    /* ID 主键 */
    id: number;
    /* 标题 */
    title: string;
    /* 内容 */
    content: string;
    /* 是否已发布 */
    pubished: boolean;
    /* 作者id */
    authorId: number;
    /* 标签id */
    tagId?: number | null;
};

/* Model Post Relation All */
export type PostRelation = {
    /* 作者 */
    author: User;
    /* 标签 */
    Tag?: Tag | null;
};

/* Model Post Relation Author */
export type PostAuthorRelation = {
    /* 作者 */
    author: User;
};

/* Model Post Relation Tag */
export type PostTagRelation = {
    /* 标签 */
    Tag?: Tag | null;
};

/* Model 标签 */
export type TagFull = {
    /* ID */
    id: number;
    /* 名字 */
    name: string;
    /* 关联文章列表 */
    posts: Post[];
    /* 关联用户 */
    User: User;
    /* 关联用户id */
    userId: number;
};

/* Model 标签 */
export type Tag = {
    /* ID */
    id: number;
    /* 名字 */
    name: string;
    /* 关联用户id */
    userId: number;
};

/* Model Tag Relation All */
export type TagRelation = {
    /* 关联文章列表 */
    posts: Post[];
    /* 关联用户 */
    User: User;
};

/* Model Tag Relation Posts */
export type TagPostsRelation = {
    /* 关联文章列表 */
    posts: Post[];
};

/* Model Tag Relation User */
export type TagUserRelation = {
    /* 关联用户 */
    User: User;
};