// Generated by prisma-generator-tsrpc v1.0.13



/* Model 用户 */
export type UserFull = {
    /* ID 主键 */
    id: number;
    /* uid */
    uid: string;
    /* 昵称 */
    nickName: string;
    /* 用户名 */
    username: string;
    /* 密码 */
    password: string;
    /* 文章 */
    posts: Post[];
    /* 权限 */
    roles: string[];
    /* 创建时间 */
    createTime: Date;
    /* 修改时间 */
    updateTime?: Date | null;
    /* 标签 */
    Tag: Tag[];
};

/* Model 用户 */
export type User = {
    /* ID 主键 */
    id: number;
    /* uid */
    uid: string;
    /* 昵称 */
    nickName: string;
    /* 用户名 */
    username: string;
    /* 密码 */
    password: string;
    /* 权限 */
    roles: string[];
    /* 创建时间 */
    createTime: Date;
    /* 修改时间 */
    updateTime?: Date | null;
};

/* Model User Relation All */
export type UserRelation = {
    /* 文章 */
    posts: Post[];
    /* 标签 */
    Tag: Tag[];
};

/* Model User Relation Posts */
export type UserPostsRelation = {
    /* 文章 */
    posts: Post[];
};

/* Model User Relation Tag */
export type UserTagRelation = {
    /* 标签 */
    Tag: Tag[];
};

/* Model 文章 */
export type PostFull = {
    /* ID 主键 */
    id: number;
    /* 标题 */
    title: string;
    /* 内容 */
    content: string;
    /* 是否已发布 */
    pubished: boolean;
    /* 作者 */
    author: User;
    /* 作者id */
    authorId: string;
    /* 创建时间 */
    createTime: Date;
    /* 修改时间 */
    updateTime?: Date | null;
    Post_Tag: Post_Tag[];
};

/* Model 文章 */
export type Post = {
    /* ID 主键 */
    id: number;
    /* 标题 */
    title: string;
    /* 内容 */
    content: string;
    /* 是否已发布 */
    pubished: boolean;
    /* 作者id */
    authorId: string;
    /* 创建时间 */
    createTime: Date;
    /* 修改时间 */
    updateTime?: Date | null;
};

/* Model Post Relation All */
export type PostRelation = {
    /* 作者 */
    author: User;
    Post_Tag: Post_Tag[];
};

/* Model Post Relation Author */
export type PostAuthorRelation = {
    /* 作者 */
    author: User;
};

/* Model Post Relation Post_Tag */
export type PostPost_TagRelation = {
    Post_Tag: Post_Tag[];
};

/* Model undefined */
export type Post_TagFull = {
    post: Post;
    tag: Tag;
    postId: number;
    tagId: number;
};

/* Model undefined */
export type Post_Tag = {
    postId: number;
    tagId: number;
};

/* Model Post_Tag Relation All */
export type Post_TagRelation = {
    post: Post;
    tag: Tag;
};

/* Model Post_Tag Relation Post */
export type Post_TagPostRelation = {
    post: Post;
};

/* Model Post_Tag Relation Tag */
export type Post_TagTagRelation = {
    tag: Tag;
};

/* Model 标签 */
export type TagFull = {
    /* ID */
    id: number;
    /* 名字 */
    name: string;
    /* 用户 */
    user: User;
    /* 用户id */
    userId: string;
    /* 创建时间 */
    createTime: Date;
    Post_Tag: Post_Tag[];
};

/* Model 标签 */
export type Tag = {
    /* ID */
    id: number;
    /* 名字 */
    name: string;
    /* 用户id */
    userId: string;
    /* 创建时间 */
    createTime: Date;
};

/* Model Tag Relation All */
export type TagRelation = {
    /* 用户 */
    user: User;
    Post_Tag: Post_Tag[];
};

/* Model Tag Relation User */
export type TagUserRelation = {
    /* 用户 */
    user: User;
};

/* Model Tag Relation Post_Tag */
export type TagPost_TagRelation = {
    Post_Tag: Post_Tag[];
};