// Generated by prisma-generator-tsrpc v1.0.13



/* Model 用户 */
export type UserFull = {
    /* 主键 */
    id: string;
    /* 用户名 */
    username: string;
    /* 密码 */
    password: string;
    /* 创建时间 */
    createAt: Date;
    /* 更新时间 */
    updateAt: Date;
    /* 用户角色 */
    roles: string[];
    /* 用户信息 */
    profile?: Profile | null;
    /* 用户文章 */
    posts: Post[];
    /* 用户标签 */
    tags: Tag[];
};

/* Model 用户 */
export type User = {
    /* 主键 */
    id: string;
    /* 用户名 */
    username: string;
    /* 密码 */
    password: string;
    /* 创建时间 */
    createAt: Date;
    /* 更新时间 */
    updateAt: Date;
    /* 用户角色 */
    roles: string[];
};

/* Model User Relation All */
export type UserRelation = {
    /* 用户信息 */
    profile?: Profile | null;
    /* 用户文章 */
    posts: Post[];
    /* 用户标签 */
    tags: Tag[];
};

/* Model User Relation Profile */
export type UserProfileRelation = {
    /* 用户信息 */
    profile?: Profile | null;
};

/* Model User Relation Posts */
export type UserPostsRelation = {
    /* 用户文章 */
    posts: Post[];
};

/* Model User Relation Tags */
export type UserTagsRelation = {
    /* 用户标签 */
    tags: Tag[];
};

/* Model 用户信息 */
export type ProfileFull = {
    /* 主键 */
    id: number;
    /* 用户昵称 */
    nickname: string;
    /* 头像 */
    avatar: string;
    /* 创建时间 */
    createdAt: Date;
    /* 更新时间 */
    updatedAt: Date;
    /* 绑定的用户 */
    user: User;
    /* 绑定的用户id */
    userId: string;
};

/* Model 用户信息 */
export type Profile = {
    /* 主键 */
    id: number;
    /* 用户昵称 */
    nickname: string;
    /* 头像 */
    avatar: string;
    /* 创建时间 */
    createdAt: Date;
    /* 更新时间 */
    updatedAt: Date;
    /* 绑定的用户id */
    userId: string;
};

/* Model Profile Relation All */
export type ProfileRelation = {
    /* 绑定的用户 */
    user: User;
};

/* Model Profile Relation User */
export type ProfileUserRelation = {
    /* 绑定的用户 */
    user: User;
};

/* Model 文章 */
export type PostFull = {
    /* 主键 */
    id: number;
    /* 文章标题 */
    title: string;
    /* 文章内容 */
    content: string;
    /* 创建时间 */
    createdAt: Date;
    /* 更新时间 */
    updatedAt: Date;
    /* 作者 */
    author: User;
    /* 作者id */
    authorId: string;
    /* 是否发布 */
    published: boolean;
    /* 发布时间 */
    publishedAt?: Date | null;
    /* 文章标签 */
    tags: PostTag[];
};

/* Model 文章 */
export type Post = {
    /* 主键 */
    id: number;
    /* 文章标题 */
    title: string;
    /* 文章内容 */
    content: string;
    /* 创建时间 */
    createdAt: Date;
    /* 更新时间 */
    updatedAt: Date;
    /* 作者id */
    authorId: string;
    /* 是否发布 */
    published: boolean;
    /* 发布时间 */
    publishedAt?: Date | null;
};

/* Model Post Relation All */
export type PostRelation = {
    /* 作者 */
    author: User;
    /* 文章标签 */
    tags: PostTag[];
};

/* Model Post Relation Author */
export type PostAuthorRelation = {
    /* 作者 */
    author: User;
};

/* Model Post Relation Tags */
export type PostTagsRelation = {
    /* 文章标签 */
    tags: PostTag[];
};

/* Model 文章标签 */
export type TagFull = {
    /* 主键 */
    id: number;
    /* 标签名 */
    name: string;
    /* 关联文章 */
    posts: PostTag[];
    /* 作者 */
    user: User;
    /* 作者id */
    userId: string;
};

/* Model 文章标签 */
export type Tag = {
    /* 主键 */
    id: number;
    /* 标签名 */
    name: string;
    /* 作者id */
    userId: string;
};

/* Model Tag Relation All */
export type TagRelation = {
    /* 关联文章 */
    posts: PostTag[];
    /* 作者 */
    user: User;
};

/* Model Tag Relation Posts */
export type TagPostsRelation = {
    /* 关联文章 */
    posts: PostTag[];
};

/* Model Tag Relation User */
export type TagUserRelation = {
    /* 作者 */
    user: User;
};

/* Model 文章标签关联表 */
export type PostTagFull = {
    /* 文章id */
    postId: number;
    /* 文章 */
    post: Post;
    /* 标签id */
    tagId: number;
    /* 标签 */
    tag: Tag;
};

/* Model 文章标签关联表 */
export type PostTag = {
    /* 文章id */
    postId: number;
    /* 标签id */
    tagId: number;
};

/* Model PostTag Relation All */
export type PostTagRelation = {
    /* 文章 */
    post: Post;
    /* 标签 */
    tag: Tag;
};

/* Model PostTag Relation Post */
export type PostTagPostRelation = {
    /* 文章 */
    post: Post;
};

/* Model PostTag Relation Tag */
export type PostTagTagRelation = {
    /* 标签 */
    tag: Tag;
};